"""simplify store_products

Revision ID: 001f2bbb467e
Revises: 2d2e640e031a
Create Date: 2026-08-16 13:32:41.774092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001f2bbb467e'
down_revision: Union[str, Sequence[str], None] = '2d2e640e031a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('unit', sa.String(length=20), nullable=True))
    op.drop_column('store_products', 'external_item_id')
    op.drop_column('store_products', 'external_product_id')
    op.drop_column('store_products', 'product_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('product_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('store_products', sa.Column('external_product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('store_products', sa.Column('external_item_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('store_products', 'unit')
    # ### end Alembic commands ###
