"""remove price_records table

Revision ID: 2d2e640e031a
Revises: 574e1c5cb2ef
Create Date: 2026-08-16 12:06:57.355684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d2e640e031a'
down_revision: Union[str, Sequence[str], None] = '574e1c5cb2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_records_record_date'), table_name='price_records')
    op.drop_index(op.f('ix_price_records_store_product_id'), table_name='price_records')
    op.drop_table('price_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('selling_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], name=op.f('price_records_store_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_records_pkey')),
    sa.UniqueConstraint('store_product_id', 'record_date', name=op.f('uq_price_record_store_product_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_price_records_store_product_id'), 'price_records', ['store_product_id'], unique=False)
    op.create_index(op.f('ix_price_records_record_date'), 'price_records', ['record_date'], unique=False)
    # ### end Alembic commands ###
