"""add supplier price tracking tables

Revision ID: 3997dda536d3
Revises: 28fa660e7718
Create Date: 2026-09-28 19:43:00.967823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3997dda536d3'
down_revision: Union[str, Sequence[str], None] = '28fa660e7718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invoice_key', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_key'), 'invoices', ['invoice_key'], unique=True)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('supplier_product_code', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'supplier_product_code', name='uq_supplier_product_code')
    )
    op.create_index(op.f('ix_supplier_products_barcode'), 'supplier_products', ['barcode'], unique=False)
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('supplier_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('discount_per_unit', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('net_unit_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_price_history_invoice_id'), 'supplier_price_history', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_supplier_price_history_supplier_product_id'), 'supplier_price_history', ['supplier_product_id'], unique=False)
    op.add_column('suppliers', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column(
        'suppliers',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )
    op.create_index(op.f('ix_suppliers_tax_id'), 'suppliers', ['tax_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_tax_id'), table_name='suppliers')
    op.drop_column('suppliers', 'is_active')
    op.drop_column('suppliers', 'tax_id')
    op.drop_index(op.f('ix_supplier_price_history_supplier_product_id'), table_name='supplier_price_history')
    op.drop_index(op.f('ix_supplier_price_history_invoice_id'), table_name='supplier_price_history')
    op.drop_table('supplier_price_history')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_barcode'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_key'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
