"""add payment_status to expenses

Revision ID: 4008fa146ddb
Revises: e958f20d1b96
Create Date: 2026-06-11 03:12:42.850081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4008fa146ddb'
down_revision: Union[str, Sequence[str], None] = 'e958f20d1b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'expenses',
        sa.Column(
            'payment_status',
            sa.String(20),
            nullable=False,
            server_default=sa.text("'pending'")
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'payment_status')
    # ### end Alembic commands ###
