"""add payment_date to expenses

Revision ID: 547820558f2f
Revises: dd1aabd51738
Create Date: 2026-06-05 15:28:04.433044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547820558f2f'
down_revision: Union[str, Sequence[str], None] = 'dd1aabd51738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('expenses', sa.Column('payment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'payment_date')
    op.alter_column('expense_payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
