"""add on delete cascade

Revision ID: e958f20d1b96
Revises: ce510c409dfe
Create Date: 2026-06-08 05:07:36.734237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e958f20d1b96'
down_revision: Union[str, Sequence[str], None] = 'ce510c409dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_payments', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('expense_payments_expense_id_fkey'), 'expense_payments', type_='foreignkey')
    op.create_foreign_key(None, 'expense_payments', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.alter_column('income_types', 'income_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('income_types_income_id_fkey'), 'income_types', type_='foreignkey')
    op.create_foreign_key(None, 'income_types', 'incomes', ['income_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income_types', type_='foreignkey')
    op.create_foreign_key(op.f('income_types_income_id_fkey'), 'income_types', 'incomes', ['income_id'], ['id'])
    op.alter_column('income_types', 'income_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'expense_payments', type_='foreignkey')
    op.create_foreign_key(op.f('expense_payments_expense_id_fkey'), 'expense_payments', 'expenses', ['expense_id'], ['id'])
    op.alter_column('expense_payments', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
